language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
sudo: false
notifications:
  email: false
  slack:
    secure: sK1g7D0xsF4Jtl0jZ2iML3Yz1nLGLIVeOcvbv2eJjIEXvEWVeO68w2gWZkjIOqM+xOj7wC/cuLF+v612Ix/ecmC3rsEZb+BQ8GBNgNa11S4rjviYJWuYJgjMrDX88M1hsXVpsFKGp1Cah+ONqxtZUsNWithXc1PhF0pRJ6S0kXXJSFGxGtuPI6twNlHZOwJY6u7PLAxGSUm5Ud5/CYdFrHvSq6fPtkaH3RMy8LE1iIcSsnWjW67hl8/PLE7GLrt7BiiSajSODYAxZD/s+tZTKFImvcA5OpmAglWYddZ9aaeJPbCcZmLlwtfanypwlhbnu09i506TWeG1L9jO2NlH2ozxThYSDWGXhb265pcgdzcG+Qpaw/GNketo1iQDBq9Y/LrQCd2pY2ov2M68lQGVmPv/qGNUOVP0WHmQ/t62tURlKjpConwxqdh8YvFBAz4ou/JA7kvxuRkRBbaWRxcAntXiENGzGF8K4kUEMdSIQ3c676w5Oo1/rkY8BMXGOU47vDm1VU/u0ibRMLc1Opg7qyHL2712q1u/af0D4W6v9NQa73++bv4UQDo3pASEn5ThwfUvtzhjUSRB3DnTtseiTrQzJ/gWj/3BIzi3JDRW8tpAqz0yAD6oCyjm1VrJrKu5ZBHLH0tF9vwm6cAeOTLoRFwEhqzmiV1KiRMXBsjxxQ8=
services:
- mongodb
script:
- "./gradlew test"
